// Code generated by "stringer -type Token"; DO NOT EDIT

package log

import "fmt"

const _Token_name = "TokenCommentTokenWordTokenLBraceTokenRBraceTokenCommaTokenNumberTokenFlagTokenStringTokenEqualsTokenGTTokenLTTokenIdentifierTokenWhitespaceTokenNewLineTokenIllegalTokenUnterminatedStringTokenEOF"

var _Token_index = [...]uint8{0, 12, 21, 32, 43, 53, 64, 73, 84, 95, 102, 109, 124, 139, 151, 163, 186, 194}

func (i Token) String() string {
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return fmt.Sprintf("Token(%d)", i)
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
