// Code generated by "stringer -type Token"; DO NOT EDIT

package log

import "fmt"

const _Token_name = "TokenCommentTokenWordTokenSentTokenRecvTokenZeroTokenLBraceTokenRBraceTokenCommaTokenNumberTokenFlagTokenValueTokenIdentifierTokenWhitespaceTokenNewLineTokenIllegalTokenEOF"

var _Token_index = [...]uint8{0, 12, 21, 30, 39, 48, 59, 70, 80, 91, 100, 110, 125, 140, 152, 164, 172}

func (i Token) String() string {
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return fmt.Sprintf("Token(%d)", i)
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
